### PR TITLE
Add to OSD error reporting

### PR DESCRIPTION
**Pull request by brownag**
This extends OSD error checking to look for duplicated sections via a new script called during post-processing step: _osd-sections.R_

### CODE REVIEW

**Comment by brownag** [comment]
This will close #49. In #50 I made all the possible adjustments that were easy/didn't have unintended impacts, which was first phase of addressing #49. What remains are mostly intractable errors related to [resence/absence of headers and/or how sections (capitalized header with a colon) are named/duplicated. If any additional error reporting is needed to address problems from #49 they will be implemented in typical-pedon.R or osd-sections.R as needed

**Comment by brownag** [comment]
OK, so the first commit switched to the new SC db. More changes than expected there due to all the series that changed ownership from Portland -> Wasilla. 

I also typo'd the new script name in the workflow file... so it didn't run. Its like I planned it that way, as it would have been frightening to see all those changes in parallel with the others. Fix incoming

**Comment by brownag** [comment]
Also, a bit of a bummer that the timestamp is converted to just the year now that we use `get_soilseries_from_NASISWebReport()` in OSD Registry to get SC DB. I really would prefer we not put calculated, nonstandard values in standard column names...

**Review by brownag — COMMENTED** [review]
ok fixed that

**Comment by dylanbeaudette** [comment]
This looks really great, thanks for making the changes. Would like to confirm that the increase in OSDs flagged for problems in the typical pedon section is related to the updated parsing code "finding" more horizons, previous missed.

image

The SRSS are going to have questions for me next week: many have been racing to get their region's OSDs down to 0 in this scoresheet.

**Comment by brownag** [comment]
> Would like to confirm that the increase in OSDs flagged for problems in the typical pedon section is related to the updated parsing code "finding" more horizons, previous missed.

That's correct!

**Pull request merged**
