### PR TITLE
Parse effervescence classes from typical pedon horizon narratives

### PR DESCRIPTION
**Pull request by dylanbeaudette**
Simple update to OSD parsing to include effervescence classes. Seems to work with and without mention of these classes. Basic tests included.

Unresolved: how will changing the structure of data returned by `SoilKnowledgeBase:::.extractHzData()` affect things downstream? 

I'll update SoilWeb / `fetchOSD()` after this gets merged.

### CODE REVIEW

**Comment by brownag** [comment]
Nice. I had been working on a suite of additional data elements on a local branch https://github.com/ncss-tech/SoilKnowledgeBase/tree/osd-parse-new1 but not tested enough to release yet. I did not include effervescence in that set, so this PR is a good addition.

There shouldn't be any downstream issues from adding new data elements to the output of `SoilKnowledgeBase:::.extractHzData()`

**Comment by dylanbeaudette** [comment]
Great. Glad you have been thinking about improvements for the OSD parsing. I bet that some of my old code can be updated / adapted as well.

**Comment by brownag** [comment]
OK, this is good to merge. I will try and incorporate the other data elements (updates to structure, roots, pores, CF volume numeric, stickiness, plasticity) in that branch in a series of PRs like this one soon

**Comment by dylanbeaudette** [comment]
Great, thanks!

**Comment by dylanbeaudette** [comment]
Closing thought: should `NA` be replaced with 'noneffervescent'?

**Comment by brownag** [comment]
> Closing thought: should `NA` be replaced with 'noneffervescent'?

Probably not... I just looked and there are a sizable number (n=3683, or 2.5% of 141655 parsed horizons) where horizon designations have "k" "kk" or "ca" suffix with `NA` effervescence.

**Comment by brownag** [comment]
Ah, actually, some of those use a slightly different phrasing e.g. "strong effervesence" instead of "strongly effervescent"... may need some additional logic to catch those and convert them to standard classes.

**Comment by dylanbeaudette** [comment]
> Ah, actually, some of those use a slightly different phrasing e.g. "strong effervesence" instead of "strongly effervescent"... may need some additional logic to catch those and convert them to standard classes.

In reviewing / updating OSDs over the years I've noticed this kind of shift in all of the classes. Open to suggestions on how to be more accommodating. The pH classes are similarly affected.

**Comment by brownag** [comment]
> Open to suggestions on how to be more accommodating. The pH classes are similarly affected.

For these cases that use `.findClass()`/`stringi::stri_detect_fixed()` the simplest solution would be adding known variants to the set of patterns, and then explicitly writing rules to convert them to some other standard class before creating ordered factors etc.

In some of the other properties we are using regex (not fixed) and capture groups, which allows more flexiblity, but still the decisions e.g. "strong effervesence" => "strongly effervescent" needs to be made somewhere, or we have to just be returning a free-form field rather than an ordered factor.

**Pull request merged**
